src/accounts/urls.py
from django.urls import path
from .views import (login, register, logout, dashboard)
app_name = "accounts"
urlpatterns = [
    path('login', login, name="login"),
    path('register', register, name="register"),
    path('dashboard', dashboard, name="dashboard"),
    path('logout', logout, name="logout")
]

src/basmoti/urls.py
from django.urls import path
from basmoti.views import (basmoti_home)
app_name = "basmoti"

urlpatterns = [
    path('', basmoti_home, name="b_home")
]

src/btre/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls')),
    path('listings/', include('listings.urls')),
    path('basmoti/', include('basmoti.urls')),
    path('imgupload/', include('imgUpload.urls')),
    path('account/', include('accounts.urls'))
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/imgUpload/urls.py
from django.urls import path
from .views import (imgCompress)

app_name = "imgupload"
urlpatterns = [
    path('', imgCompress, name="imgcompress")
]

src/listings/urls.py
from django.urls import path

from listings.views import (
    search,
    listings,
    listing
)

app_name = "listings"

urlpatterns = [
    path('', listings, name="listings"),
    path('<int:listing_id>', listing, name="listing"),
    path('search/', search, name='search')
]

src/pages/urls.py
from django.urls import include, path
from pages.views import (index, about)

app_name = "pages"

urlpatterns = [
    path('', index, name="index"),
    path('about/', about, name="about")
]

src/basmoti/models.py
from django.db import models

# Create your models here.

src/contacts/models.py
from django.db import models
from datetime import datetime
# Create your models here.


class Contact(models.Model):
    listing = models.CharField(max_length=200)
    listing_id = models.IntegerField()
    name = models.CharField(max_length=200)
    email = models.CharField(max_length=100)
    phone = models.CharField(max_length=100)
    message = models.TextField(blank=True)
    contact_date = models.DateTimeField(default=datetime.now)
    user_id = models.IntegerField(blank=True)

    def __str__(self):
        return self.name

src/imgUpload/models.py
from django.db import models
from PIL import Image

# Create your models here.


class Imgcompress(models.Model):
    img = models.ImageField(
        upload_to="imgupload/compress/", blank=True)

    def save(self):
        super().save()  # saving image first

        image = Image.open(self.img.path)  # Open image using self

        if image.height > 300 or image.width > 300:
            new_img = (300, 300)
            image.thumbnail(new_img)
            image.save(self.img.path)

src/listings/models.py
from django.db import models
from datetime import datetime
from realtors.models import Realtor


class Listing(models.Model):
    realtor = models.ForeignKey(Realtor,  on_delete=models.DO_NOTHING)
    title = models.CharField(max_length=200)
    address = models.CharField(max_length=100)
    city = models.CharField(max_length=100)
    state = models.CharField(max_length=100)
    zipcode = models.CharField(max_length=20)
    description = models.TextField(blank=True)
    price = models.IntegerField()
    bedrooms = models.IntegerField()
    bathrooms = models.DecimalField(max_digits=2, decimal_places=1)
    garage = models.IntegerField(default=0)
    sqft = models.IntegerField()
    lot_size = models.DecimalField(max_digits=5, decimal_places=1)
    photo_main = models.ImageField(upload_to='photos/%Y/%m/%d/')
    photo_1 = models.ImageField(upload_to='photos/%Y/%m/%d/', blank=True)
    photo_2 = models.ImageField(upload_to='photos/%Y/%m/%d/', blank=True)
    photo_3 = models.ImageField(upload_to='photos/%Y/%m/%d/', blank=True)
    photo_4 = models.ImageField(upload_to='photos/%Y/%m/%d/', blank=True)
    photo_5 = models.ImageField(upload_to='photos/%Y/%m/%d/', blank=True)
    photo_6 = models.ImageField(upload_to='photos/%Y/%m/%d/', blank=True)
    is_published = models.BooleanField(default=True)
    list_date = models.DateTimeField(default=datetime.now, blank=True)

    def __str__(self):
        return self.title

src/realtors/models.py
from django.db import models
from datetime import datetime


class Realtor(models.Model):
    name = models.CharField(max_length=200)
    photo = models.ImageField(upload_to='photos/%Y/%m/%d/')
    description = models.TextField(blank=True)
    phone = models.CharField(max_length=20)
    email = models.CharField(max_length=50)
    is_mvp = models.BooleanField(default=False)
    hire_date = models.DateTimeField(default=datetime.now, blank=True)

    def __str__(self):
        return self.name

src/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth.models import User, auth

# Create your views here.


def login(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = auth.authenticate(username=username, password=password)

        if user is not None:
            auth.login(request, user)
            messages.success(request, "log in")
            return redirect('accounts:dashboard')
        else:
            messages.error(request, "not login")
            return redirect('login')
    else:
        return render(request, 'accounts/login.html')


def register(request):
    if request.method == 'POST':
        first_name = request.POST['first_name']
        last_name = request.POST['last_name']
        username = request.POST['username']
        email = request.POST['email']
        password = request.POST['password']
        password2 = request.POST['password2']

        if password == password2:
            if User.objects.filter(username=username).exists():
                messages.error(request, "The user name already taken")
                return redirect('accounts:register')
            else:
                if User.objects.filter(email=email).exists():
                    messages.error(request, "The email name already taken")
                    return redirect('accounts:register')
                else:
                    # looks good
                    user = User.objects.create_user(
                        first_name=first_name, last_name=last_name, username=username, email=email, password=password)
                    # auth.login(request, user)
                    # messages.success(request, "You are now loged in")
                    # return redirect('index')
                    user.save()
                    messages.success(request, "You are now loged in")
                    return redirect('accounts:login')
        else:
            messages.error(request, 'Passwords do not match')
            return redirect('accounts:register')
    else:
        return render(request, 'accounts/register.html')

    return render(request, 'accounts/register.html')


def logout(request):
    if request.method == 'POST':
        auth.logout(request)
        messages.error(request, 'you are logout')
    return redirect('pages:index')


def dashboard(request):
    return render(request, 'accounts/dashboard.html')

src/basmoti/views.py
from django.shortcuts import render
# fromm django.http import h
# Create your views here.


def basmoti_home(request):
    return render(request, 'basmoti/index.html')

src/contacts/views.py
from django.shortcuts import render

# Create your views here.

src/imgUpload/views.py
from django.shortcuts import render

# Create your views here.


def imgCompress(request):
    return render(request, 'imgupload/index.html')

src/listings/views.py
from django.shortcuts import render
from listings.models import Listing
# Create your views here.


def listings(request):
    context = {}
    listings = Listing.objects.all()
    context = {
        "listings": listings
    }
    return render(request, 'listings/listings.html', context)


def listing(request, listing_id):
    return render(request, 'listings/listing.html')


def search(request):
    return render(request, 'listings/search.html')

src/pages/views.py
from django.shortcuts import render
from django.http import HttpResponse
# Create your views here.


def index(request):
    return render(request, 'pages/index.html')


def about(request):
    return render(request, 'pages/about.html')

src/realtors/views.py
from django.shortcuts import render

# Create your views here.

src/templates/accounts/dashboard.html
{% extends 'base.html' %}
{% block content %}

<section id="showcase-inner" class="py-5 text-white">
    <div class="container">
        <div class="row text-center">
            <div class="col-md-12">
                <h1 class="display-4">User Dashboard</h1>
                <p class="lead">Manage your BT Real Estate account</p>
            </div>
        </div>
    </div>
</section>

<!-- Breadcrumb -->
<section id="bc" class="mt-3">
    <div class="container">
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item">
                    <a href="{% url 'pages:index' %}">
                        <i class="fas fa-home"></i> Home</a>
                </li>
                <li class="breadcrumb-item active"> Dashboard</li>
            </ol>
        </nav>
    </div>
</section>

<section id="dashboard" class="py-4">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h2>Welcome John</h2>
                <p>Here are the property listings that you have inquired about</p>
                <table class="table">
                    <thead>
                        <tr>
                            <th scope="col">#</th>
                            <th scope="col">Property</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>22</td>
                            <td>45 Drivewood Circle</td>
                            <td>
                                <a class="btn btn-light" href="#">View Listing</a>
                            </td>
                        </tr>
                        <tr>
                            <td>43</td>
                            <td>22 Westbrook rd</td>
                            <td>
                                <a class="btn btn-light" href="#">View Listing</a>
                            </td>
                        </tr>
                        <tr>
                            <td>31</td>
                            <td>12 Samson Ave</td>
                            <td>
                                <a class="btn btn-light" href="#">View Listing</a>
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</section>

{% endblock %}

src/templates/accounts/login.html
{% extends 'base.html' %}
{% load static %}
{% block content%}
    <section id="login" class="bg-light py-5">
        <div class="container">
        <div class="row">
            <div class="col-md-6 mx-auto">
            <div class="card">
                <div class="card-header bg-primary text-white">
                <h4>
                    <i class="fas fa-sign-in-alt"></i> Login</h4>
                </div>
                <div class="card-body">
                {% include 'partials/_alert.html' %}
                <form action="{% url 'accounts:login' %}" method="POST"> {% csrf_token %}
                    <div class="form-group">
                    <label for="username">Username</label>
                    <input type="text" name="username" class="form-control" required>
                    </div>

                    <div class="form-group">
                    <label for="password2">Password</label>
                    <input type="password" name="password" class="form-control" required>
                    </div>

                    <input type="submit" value="Login" class="btn btn-secondary btn-block">
                </form>
                </div>
            </div>
            </div>
        </div>
        </div>
    </section>
{% endblock content%}

src/templates/accounts/register.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<section id="register" class="bg-light py-5">
	<div class="container">
		<div class="row">
			<div class="col-md-6 mx-auto">
				<div class="card">
					<div class="card-header bg-primary text-white">
						<h4><i class="fas fa-user-plus"></i> Register</h4>
					</div>
					<div class="card-body">
                        {% include 'partials/_alert.html' %}
						<form action="{% url 'accounts:register' %}" method="POST"> {% csrf_token %}
							<div class="form-group">
								<label for="first_name">First Name</label>
								<input type="text" name="first_name" class="form-control" required />
							</div>
							<div class="form-group">
								<label for="last_name">Last Name</label>
								<input type="text" name="last_name" class="form-control" required />
							</div>
							<div class="form-group">
								<label for="username">Username</label>
								<input type="text" name="username" class="form-control" required />
							</div>
							<div class="form-group">
								<label for="email">Email</label>
								<input type="email" name="email" class="form-control" required />
							</div>
							<div class="form-group">
								<label for="password2">Password</label>
								<input type="password" name="password" class="form-control" required />
							</div>
							<div class="form-group">
								<label for="password">Confirm Password</label>
								<input type="password" name="password2" class="form-control" required />
							</div>
							<input type="submit" value="Register" class="btn btn-secondary btn-block" />
						</form>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>
{% endblock content %}

src/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="{% static 'css/all.css' %}">
    <!-- Bootstrap -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <!-- Custom -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <!-- Light Box -->
    <link rel="stylesheet" href="{% static 'css/lightbox.min.css' %}">
    <title>BT Real Estate</title>
</head>

<body>
    <!-- topbar -->
    {% include 'partials/_topbar.html' %}
    <!-- navbar -->
    {% include 'partials/_navbar.html' %}
    {% block content %}{% endblock %}
    <!-- footer -->
    {% include 'partials/_footer.html' %} 
    <!-- Scripts -->
    <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>
</body>

</html>

src/templates/basmoti/basmoti/index-2.html
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>2CBCB280174C95BB</RequestId><HostId>zHfR+pE7D8FmNFVHXO1XvoOCct0DbwYQGx65H+4pxLRlNMKNccm62++qUzzJTzkt8tFFW+k/VUo=</HostId></Error>

src/templates/basmoti/basmoti/product-details.html
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>3EE76D3F485AA56F</RequestId><HostId>EpxYhh/LJVA/Sa7UkKnEQ4SddHuOqWPcEULtUTY6WtRk3nC7zPYg9UiGAcs59DjT/OX6Tg5B1dA=</HostId></Error>

src/templates/imgupload/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0" />
		<title>Image Upload</title>
	</head>
	<body>
        <form action="{% url 'imgupload:imgcompress' %}" method="POST">
            <input type="file" />
            <button type="submit">Upload</button>
        </form>
    
    </body>
</html>

src/templates/listings/listing.html
{% extends 'base.html' %}
{% block content %}
listing
{% endblock content %}

src/templates/listings/listings.html
{% extends 'base.html' %} {% load static %}
{% load humanize %}
{% block content %}

<section id="showcase-inner" class="py-5 text-white">
	<div class="container">
		<div class="row text-center">
			<div class="col-md-12">
				<h1 class="display-4">Browse Our Properties</h1>
				<p class="lead">Lorem ipsum dolor sit, amet consectetur adipisicing elit. Sunt, pariatur!</p>
			</div>
		</div>
	</div>
</section>

<!-- Breadcrumb -->
<section id="bc" class="mt-3">
	<div class="container">
		<nav aria-label="breadcrumb">
			<ol class="breadcrumb">
				<li class="breadcrumb-item">
					<a href="{% url 'pages:index' %}"> <i class="fas fa-home"></i> Home</a>
				</li>
				<li class="breadcrumb-item active">Browse Listings</li>
			</ol>
		</nav>
	</div>
</section>

<!-- Listings -->
<section id="listings" class="py-4">
	<div class="container">
		<div class="row">
			{% if listings %}
				{% for listing in listings  %}
					<!-- Listing 1 -->
					<div class="col-md-6 col-lg-4 mb-4">
						<div class="card listing-preview">
							<img class="card-img-top" src="{{ listing.photo_main.url }}" alt="" />
							<div class="card-img-overlay">
								<h2>
									<span class="badge badge-secondary text-white">$ {{ listing.price|intcomma }} </span>
								</h2>
							</div>
							<div class="card-body">
								<div class="listing-heading text-center">
									<h4 class="text-primary">{{ listing.title }}</h4>
									<p><i class="fas fa-map-marker text-secondary"></i> {{listing.city}} {{listing.state}},{{listing.zipcode}}</p>
								</div>
								<hr />
								<div class="row py-2 text-secondary">
									<div class="col-6"><i class="fas fa-th-large"></i> Sqft: 3200</div>
									<div class="col-6"><i class="fas fa-car"></i> Garage: 2</div>
								</div>
								<div class="row py-2 text-secondary">
									<div class="col-6"><i class="fas fa-bed"></i> Bedrooms: 3</div>
									<div class="col-6"><i class="fas fa-bath"></i> Bathrooms: 2</div>
								</div>
								<hr />
								<div class="row py-2 text-secondary">
									<div class="col-12"><i class="fas fa-user"></i> Kyle Brown</div>
								</div>
								<div class="row text-secondary pb-2">
									<div class="col-6"><i class="fas fa-clock"></i> 2 days ago</div>
								</div>
								<hr />
								<a href="{% url 'listings:listing' listing.id %}" class="btn btn-primary btn-block">More Info</a>
							</div>
						</div>
					</div>
				{% endfor %}
				
			{% else %}
				<h1>No Listings Data</h1>
			{% endif %}
			
		</div>

		<div class="row">
			<div class="col-md-12">
				<ul class="pagination">
					<li class="page-item disabled">
						<a class="page-link" href="#">&laquo;</a>
					</li>
					<li class="page-item active">
						<a class="page-link" href="#">1</a>
					</li>
					<li class="page-item">
						<a class="page-link" href="#">2</a>
					</li>
					<li class="page-item">
						<a class="page-link" href="#">3</a>
					</li>
					<li class="page-item">
						<a class="page-link" href="#">&raquo;</a>
					</li>
				</ul>
			</div>
		</div>
	</div>
</section>

{% endblock content %}

src/templates/listings/search.html
{% extends 'base.html' %}
{% block content %}
search
{% endblock content %}

src/templates/pages/about.html
{% extends 'base.html' %} 
{% load static %}
{% block content %}

<section id="showcase-inner" class="py-5 text-white">
	<div class="container">
		<div class="row text-center">
			<div class="col-md-12">
				<h1 class="display-4">About BT Real Estate</h1>
				<p class="lead">Lorem ipsum dolor sit, amet consectetur adipisicing elit. Sunt, pariatur!</p>
			</div>
		</div>
	</div>
</section>

<!-- Breadcrumb -->
<section id="bc" class="mt-3">
	<div class="container">
		<nav aria-label="breadcrumb">
			<ol class="breadcrumb">
				<li class="breadcrumb-item">
					<a href="index.html"> <i class="fas fa-home"></i> Home</a>
				</li>
				<li class="breadcrumb-item active">About</li>
			</ol>
		</nav>
	</div>
</section>

<section id="about" class="py-4">
	<div class="container">
		<div class="row">
			<div class="col-md-8">
				<h2>We Search For The Perfect Home</h2>
				<p class="lead">Lorem ipsum dolor sit, amet consectetur adipisicing elit. Sunt, pariatur!</p>
				<img src="{% static 'img/about.jpg' %}" alt="" />
				<p class="mt-4">
					Lorem ipsum dolor sit amet consectetur adipisicing elit. Perspiciatis esse officia repudiandae ad
					saepe ex, amet neque quod accusamus rem quia magnam magni dolorum facilis ullam minima perferendis?
					Exercitationem at quaerat commodi id libero eveniet harum perferendis laborum molestias quia.
				</p>
			</div>
			<div class="col-md-4">
				<div class="card">
					<img class="card-img-top" src="{% static 'img/realtors/kyle.jpg' %}" alt="Seller of the month" />
					<div class="card-body">
						<h5 class="card-title">Seller Of The Month</h5>
						<h6 class="text-secondary">Kyle Brown</h6>
						<p class="card-text">
							Lorem ipsum dolor sit amet consectetur adipisicing elit. Omnis nesciunt amet, illo itaque
							similique repellat. content.
						</p>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>

<!-- Work -->
<section id="work" class="bg-dark text-white text-center">
	<h2 class="display-4">We Work For You</h2>
	<h4>Lorem ipsum dolor sit amet consectetur adipisicing elit. Autem velit aperiam, unde aliquid at similique!</h4>
	<hr />
	<a href="listings.html" class="btn btn-secondary text-white btn-lg">View Our Featured Listings</a>
</section>

<!-- Team -->
<section id="team" class="py-5">
	<div class="container">
		<h2 class="text-center">Our Team</h2>
		<div class="row text-center">
			<div class="col-md-4">
				<img src="{% static 'img/realtors/kyle.jpg' %}" alt="" class="rounded-circle mb-3" />
				<h4>Kyle Brown</h4>
				<p class="text-success"><i class="fas fa-award text-success mb-3"></i> Realtor</p>
				<hr />
				<p><i class="fas fa-phone"></i> (555)-555-5555</p>
				<p><i class="fas fa-envelope-open"></i> kyle@btrealestate.co</p>
			</div>

			<div class="col-md-4">
				<img src="{% static 'img/realtors/mark.jpg' %}" alt="" class="rounded-circle mb-3" />
				<h4>Mark Hudson</h4>
				<p class="text-success">Realtor</p>
				<hr />
				<p><i class="fas fa-phone"></i> (444)-444-4444</p>
				<p><i class="fas fa-envelope-open"></i> mark@btrealestate.co</p>
			</div>

			<div class="col-md-4">
				<img src="{% static 'img/realtors/jenny.jpg' %}" alt="" class="rounded-circle mb-3" />
				<h4>Jenny Johnson</h4>
				<p class="text-success">Realtor</p>
				<hr />
				<p><i class="fas fa-phone"></i> (333)-333-3333</p>
				<p><i class="fas fa-envelope-open"></i> jenny@btrealestate.co</p>
			</div>
		</div>
	</div>
</section>

{% endblock content %}

src/templates/partials/_alert.html
{% if messages %}
{% for message in messages %}
<div id="message" class="container">
    <div class="alert alert-{{message.tags}} alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert">
            <span aria-hidden="true">&times;</span>
        </button>
        <strong>
            {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
            Error
            {% else %}
            {{message.tags|title}}
            {% endif %}
        </strong>
        {{message}}
    </div>
</div>
{% endfor %}
{% endif %}

src/templates/partials/_footer.html
 <!-- Footer -->
  <footer id="main-footer" class="py-4 bg-primary text-white text-center">
    Copyright &copy;
    <span class="year"></span> BT Real Estate
  </footer>

src/templates/partials/_navbar.html
{% load static %}
<!-- Navbar -->
<nav class="navbar navbar-expand-lg navbar-dark bg-primary sticky-top">
    <div class="container">
      <a class="navbar-brand" href="{% url 'pages:index' %}">
        <img src="{% static 'img/logo.png' %}" class="logo" alt="logo">
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <ul class="navbar-nav">
          <li 
            {% if '/' == request.path %}
              class="nav-item active mr-3"
            {% else %}
              class="nav-item mr-3"
            {% endif %}
          >
            <a class="nav-link" href="{% url 'pages:index' %}">Home</a>
          </li>
          <li 
            {% if 'about' in request.path %}
              class="nav-item mr-3 active"
            {% else %}
              class="nav-item mr-3"
            {% endif %}
          >
            <a class="nav-link" href="{% url 'pages:about' %}">About</a>
          </li>
          <li 
            {% if 'listings' in request.path %}
              class="nav-item mr-3 active"
            {% else %}
              class="nav-item mr-3"
            {% endif %}
          >
            <a class="nav-link" href="{% url 'listings:listings' %}">Featured Listings</a>
          </li>
        </ul>
        {% if user.is_authenticated %}
          <ul class="navbar-nav ml-auto">
          <li 
            {% if 'register' in request.path %}
              class="nav-item mr-3 active"
            {% else %}
              class="nav-item mr-3"
            {% endif %}
          >
            <a class="nav-link" href="{% url 'accounts:dashboard' %}">
              <i class="fas fa-user-plus"></i> Welcome {{user.username}} (Dashboard)</a>
          </li>
          <li 
            {% if 'login' in request.path %}
              class="nav-item mr-3 active"
            {% else %}
              class="nav-item mr-3"
            {% endif %}
          >
            <a class="nav-link" href="javascript:{document.getElementById('logout').submit()}">
              <i class="fas fa-sign-in-alt"></i>
              Logout
            </a>
            <form method="POST" action="{% url 'accounts:logout' %}" id="logout" >{% csrf_token %}
              <input type="hidden"/>
            </form>
          </li>
        </ul>
        {% else %}
          <ul class="navbar-nav ml-auto">
          <li 
            {% if 'register' in request.path %}
              class="nav-item mr-3 active"
            {% else %}
              class="nav-item mr-3"
            {% endif %}
          >
            <a class="nav-link" href="{% url 'accounts:register' %}">
              <i class="fas fa-user-plus"></i> Register</a>
          </li>
          <li 
            {% if 'login' in request.path %}
              class="nav-item mr-3 active"
            {% else %}
              class="nav-item mr-3"
            {% endif %}
          >
            <a class="nav-link" href="{% url 'accounts:login' %}">
              <i class="fas fa-sign-in-alt"></i>
              Login</a>
          </li>
        </ul>
        {% endif %}
        
      </div>
    </div>
  </nav>

src/templates/partials/_topbar.html
<!-- Top Bar -->
    <section id="top-bar" class="p-3">
        <div class="container">
            <div class="row">
                <div class="col-md-4">
                    <i class="fas fa-phone"></i> (617)-555-5555
                </div>
                <div class="col-md-4">
                    <i class="fas fa-envelope-open"></i> contact@btrealestate.co
                </div>
                <div class="col-md-4">
                    <div class="social text-right">
                        <a href="#">
                            <i class="fab fa-twitter"></i>
                        </a>
                        <a href="#">
                            <i class="fab fa-facebook"></i>
                        </a>
                        <a href="#">
                            <i class="fab fa-linkedin"></i>
                        </a>
                        <a href="#">
                            <i class="fab fa-instagram"></i>
                        </a>
                        <a href="#">
                            <i class="fab fa-pinterest"></i>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </section>